name: Docker Image CI

on: 
  release:
    types: [created]
    
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the version
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag actions-runner:${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
